# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby '3.0.0'

gem 'oj'
gem 'minitest'
gem 'pry'
gem 'rspec-benchmark'
gem 'ruby-prof'
